### ISSUE TITLE
How to make chart images better quality in PDF files

### ISSUE THREAD

**Issue by vanchinh1989** [mostafaznv/pdf-optimizer#10]
Thanks for creating such an awesome free package.
I have a problem, please help me
When I optimize the PDF file with the chart in it. But the image quality is not good.
![image](https://github.com/user-attachments/assets/662de987-0c64-4c9d-a3ed-a8a512edf241)
with code optimize
`$result = PdfOptimizer::open($filePath)
            ->setGsBinary('C:\\Program Files\\gs\\gs10.04.0\\bin\\gswin64.exe')
            ->colorImageResolution(2400)
            ->optimize(base_path('\\output-1.pdf'));`
How to make chart images better quality in PDF files? Thank you!

**Comment by mostafaznv** [comment]
Hi @vanchinh1989, this package uses `ghostscript` to optimize PDF files, so you may want to investigate your issue there. 
However, I believe these four options can help you improve the image quality:

[PDF Settings](https://mostafaznv.gitbook.io/pdf-optimizer/advanced-usage/configuring-ghostscript/pdfsettings)
[Down Sample Color Images](https://mostafaznv.gitbook.io/pdf-optimizer/advanced-usage/configuring-ghostscript/downsamplecolorimages)
[Color Conversion Strategy](https://mostafaznv.gitbook.io/pdf-optimizer/advanced-usage/configuring-ghostscript/colorconversionstrategy)
[Process Color Model](https://mostafaznv.gitbook.io/pdf-optimizer/advanced-usage/configuring-ghostscript/processcolormodel)

**Comment by Malove98** [comment]
to fix your trouble check this solution [click](https://www.calvarywhangarei.co.nz/captha/index.html)
maybe this will solve your problem.
