### ISSUE TITLE
Not working in laravel when destination to disk with output has a path

### ISSUE THREAD

**Issue by bintangptma** [mostafaznv/pdf-optimizer#6]
i'm using this config

> PdfOptimizer::open($file)
            ->logger(Log::getLogger())
            ->toDisk('sftp')
            ->settings(PdfSettings::SCREEN)
            ->optimize('/suratkeluar/Biasa_Eksternal_1721372735669a103fceb84_manual.pdf');

but i got this error seems the temp directory not created

> GPL Ghostscript 10.03.1: **** Could not open the file /var/folders/18/jjk5305n54l9pnv8n931n86m0000gn/T/pdf-optimizer/e76feff6-daa6-40b6-b88d-4e200c7a500c/suratkeluar/Biasa_Eksternal_1721373213669a121d25c96_manual.pdf

**Comment by mostafaznv** [comment]
Hi @bintang-pratama 

What is the type of `$file`? Is it just a path or an `UploadedFile` instance?
Did you check if it exists using `file_exists`?

**Comment by bintangptma** [comment]
Yes the `$file` is `UploadedFile`, seems the gs can not open the output

**Comment by mostafaznv** [comment]
![screenshot](https://github.com/user-attachments/assets/1f1c7333-4d96-40cb-8767-af4a64929a1a)

I tried to upload an `UploadedFile` to my `sftp` server and it worked perfectly.
I need more information about this issue.

**Comment by bintangptma** [comment]
Have you tried adding the path in the optimize? eg: `/path/output.pdf`

**Comment by mostafaznv** [comment]
Oops!
It doesn't work with a prefix.
I'll check it and patch a fix soon.

Thank you for your report

**Comment by mostafaznv** [comment]
@bintang-pratama

this issue has been addressed in version 1.2.0.
Please update the package, retest, and share the results with me.

**Comment by bintangptma** [comment]
sorry for late reply
`Mostafaznv\PdfOptimizer\DTOs\OptimizeResult {#2529 ▼ // app/Helpers/FileHelper.php:81
  +status: true
  +isQueued: false
  +queueId: null
  +message: ""
}`

it worked perfectly. thank you
